export const RE_COLORS = {
  sage: "#A9CBD0",
  aqua: "#ADD6F0",
  lavender: "#C2ADF3",
  blush: "#F1C4DD",
  cream: "#F2E4DE",
  ink900: "#1B2A8C",
  ink700: "#3746A5",
  ink600: "#475FAC",
  ink500: "#5B6DA9",
  ink400: "#7E8AC0",
  ink300: "#9099CA",
  ink200: "#B4BCDD",
  appBg: "#F7FAFD",
  boardBg: "#EAF3FA",
  card: "#FFFFFF",
  soft: "#F4F7FD",
  line: "#E4EAF6",
  field: "#DDE3F2",
  pillLav: "#E3E6F7",
  pillMint: "#E7F7F6",
  pillPeach: "#FCEBE5",
  pillSage: "#CEE3E4",
  pillIndigo: "#C7CCE9",
  pink: "#E43C78",
  pinkSoft: "#FEF4F6",
  pinkLine: "#F4C2D4",
  handInk: "#4A5FC1",
};

export const RE_ASSETS = {
  logoMark: "/re-assets/logo_mark.png",
  logoLockup: "/re-assets/logo_lockup.png",
  hero: "/re-assets/hero.jpg",
  charStand: "/re-assets/char_stand.jpg",
  splashBg: "/re-assets/splash_bg.jpg",
  signupBg: "/re-assets/signup_bg.jpg",
  bgPlate: "/re-assets/bg_plate.jpg",
  sdIdle: "/re-assets/sd_idle.jpg",
  sdSorry: "/re-assets/sd_sorry.jpg",
  sdLoading: "/re-assets/sd_loading.jpg",
  sdDone: "/re-assets/sd_done.jpg",
  sdGuide: "/re-assets/sd_guide.jpg",
  sdDoneP07: "/re-assets/sd_done_p07.jpg",
  mIdle: "/re-assets/m_idle.jpg",
  mCheer: "/re-assets/m_cheer.jpg",
  mSorry: "/re-assets/m_sorry.jpg",
  mLoad: "/re-assets/m_load.jpg",
  mDone: "/re-assets/m_done.jpg",
  dEyes: "/re-assets/d_eyes.jpg",
  dPin: "/re-assets/d_pin.jpg",
  dBoots: "/re-assets/d_boots.jpg",
  dBoard: "/re-assets/d_board.jpg",
};
